// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"
	userModel "washit-api/internal/user/dto/model"

	mock "github.com/stretchr/testify/mock"

	userRequest "washit-api/internal/user/dto/request"
)

// UserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type UserServiceInterface struct {
	mock.Mock
}

// GetMe provides a mock function with given fields: ctx, userId
func (_m *UserServiceInterface) GetMe(ctx context.Context, userId string) (*userModel.User, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *userModel.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*userModel.User, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *userModel.User); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userModel.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userId
func (_m *UserServiceInterface) GetUserByID(ctx context.Context, userId string) (*userModel.User, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *userModel.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*userModel.User, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *userModel.User); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userModel.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx
func (_m *UserServiceInterface) GetUsers(ctx context.Context) ([]*userModel.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*userModel.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*userModel.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*userModel.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*userModel.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, req
func (_m *UserServiceInterface) Login(ctx context.Context, req *userRequest.Login) (*userModel.User, interface{}, interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *userModel.User
	var r1 interface{}
	var r2 interface{}
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, *userRequest.Login) (*userModel.User, interface{}, interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *userRequest.Login) *userModel.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userModel.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *userRequest.Login) interface{}); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *userRequest.Login) interface{}); ok {
		r2 = rf(ctx, req)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(interface{})
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, *userRequest.Login) error); ok {
		r3 = rf(ctx, req)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Logout provides a mock function with given fields: ctx, userId
func (_m *UserServiceInterface) Logout(ctx context.Context, userId string) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, userId
func (_m *UserServiceInterface) RefreshToken(ctx context.Context, userId string) (string, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *UserServiceInterface) Register(ctx context.Context, req *userRequest.Register) (*userModel.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *userModel.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *userRequest.Register) (*userModel.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *userRequest.Register) *userModel.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userModel.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *userRequest.Register) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMe provides a mock function with given fields: ctx, userId, req
func (_m *UserServiceInterface) UpdateMe(ctx context.Context, userId string, req *userRequest.Update) (*userModel.User, error) {
	ret := _m.Called(ctx, userId, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMe")
	}

	var r0 *userModel.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *userRequest.Update) (*userModel.User, error)); ok {
		return rf(ctx, userId, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *userRequest.Update) *userModel.User); ok {
		r0 = rf(ctx, userId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userModel.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *userRequest.Update) error); ok {
		r1 = rf(ctx, userId, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserServiceInterface creates a new instance of UserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceInterface {
	mock := &UserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
